### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by DenisPolagaev** [MaratBR/RCPOD-AirMass#3]
https://github.com/MaratBR/RCPOD-AirMass/blob/b4077f11eb577834502d19eea0395b0fd7949a9c/mkairmass.py#L139
 
Когда происходит так, что данные все одинаковые, тобишь min и max одинаковые, возникает исключение.

решение:

https://github.com/MaratBR/RCPOD-AirMass/blob/b4077f11eb577834502d19eea0395b0fd7949a9c/mkairmass.py#L633
Заменить NonFiniteRasterData: на Exception, для того чтобы при возникновении любого исключения файл помечался как ошибочный.

**Comment by DenisPolagaev** [comment]
+ Ещё бывает ошибка поиска датасета

**Comment by MaratBR** [comment]
Исправлено в ab7105c
